const express=require('express');const http=require('http');const {Server}=require('socket.io');
const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:'*'}});app.use(express.static('public'));
const rooms=new Map();
function code(){let c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join('')}
function makeRoom(name,socket){let r;do{r=code()}while(rooms.has(r));rooms.set(r,{code:r,players:[],chat:[],blackjack:null,roulette:{bets:[],spinning:false,last:null},slots:[]});joinRoom(r,name,socket);return r}
function joinRoom(r,name,socket){const room=rooms.get(r);if(!room)throw Error('Room not found'); if(room.players.length>=10)throw Error('Room full'); let player={id:socket.id,name:name.slice(0,18)||'Player',chips:100000,seat:room.players.length+1,hand:[],bet:0,status:'Lobby'};room.players.push(player);socket.join(r);socket.data.room=r;socket.data.name=name;return player}
function emitRoom(r){const room=rooms.get(r);if(room)io.to(r).emit('roomState',safe(room))}
function safe(room){return {...room,players:room.players.map(p=>({...p,hand:p.id? p.hand:[]}))}}
const suits=['♠','♥','♦','♣'], ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];function deck(){let d=[];for(const s of suits)for(const r of ranks)d.push({r,s});return d.sort(()=>Math.random()-.5)}
function val(card){if(['J','Q','K'].includes(card.r))return 10;if(card.r==='A')return 11;return +card.r}function total(hand){let t=hand.reduce((a,c)=>a+val(c),0),aces=hand.filter(c=>c.r==='A').length;while(t>21&&aces--){t-=10}return t}
function bjStart(room){let d=deck();room.blackjack={deck:d,dealer:[d.pop(),d.pop()],turn:0,active:true,message:'Blackjack started'};for(const p of room.players){p.hand=[d.pop(),d.pop()];p.bet=1000;p.chips-=1000;p.status='Playing'}}
function bjFinish(room){const bj=room.blackjack;const dealer=bj.dealer;while(total(dealer)<17)dealer.push(bj.deck.pop());const dt=total(dealer);for(const p of room.players){const pt=total(p.hand); if(pt<=21&&(dt>21||pt>dt)){p.chips+=p.bet*2;p.status='Won'}else if(pt===dt&&pt<=21){p.chips+=p.bet;p.status='Push'}else p.status='Lost';p.bet=0}bj.active=false;bj.message='Round complete'}
io.on('connection',socket=>{socket.on('createRoom',(name,cb)=>{try{let r=makeRoom(name,socket);cb({ok:true,code:r});emitRoom(r)}catch(e){cb({ok:false,error:e.message})}});socket.on('joinRoom',({code,name},cb)=>{try{code=(code||'').toUpperCase().trim();joinRoom(code,name,socket);cb({ok:true,code});emitRoom(code)}catch(e){cb({ok:false,error:e.message})}});socket.on('chat',msg=>{const r=socket.data.room,room=rooms.get(r);if(!room)return;room.chat.push({name:socket.data.name,msg:String(msg).slice(0,120)});emitRoom(r)});
socket.on('bjStart',()=>{const room=rooms.get(socket.data.room);if(!room)return;bjStart(room);emitRoom(room.code)});socket.on('bjHit',()=>{const room=rooms.get(socket.data.room),p=room?.players.find(x=>x.id===socket.id);if(!room?.blackjack?.active||!p)return;p.hand.push(room.blackjack.deck.pop());if(total(p.hand)>21)p.status='Bust';emitRoom(room.code)});socket.on('bjStand',()=>{const room=rooms.get(socket.data.room),p=room?.players.find(x=>x.id===socket.id);if(!room?.blackjack?.active||!p)return;p.status='Stand';if(room.players.every(x=>['Stand','Bust'].includes(x.status)))bjFinish(room);emitRoom(room.code)});
socket.on('spinSlots',(bet,cb)=>{const room=rooms.get(socket.data.room),p=room?.players.find(x=>x.id===socket.id);bet=Math.max(100,Math.min(+bet||100,5000,p?.chips||0));if(!p)return cb({ok:false});p.chips-=bet;const icons=['🍒','🍋','🔔','💎','7️⃣','⭐'];const roll=[0,1,2].map(()=>icons[Math.floor(Math.random()*icons.length)]);let win=0;if(roll[0]===roll[1]&&roll[1]===roll[2])win=bet*10;else if(roll[0]===roll[1]||roll[1]===roll[2]||roll[0]===roll[2])win=bet*2;p.chips+=win;cb({ok:true,roll,win});emitRoom(room.code)});
socket.on('rouletteBet',({bet,choice},cb)=>{const room=rooms.get(socket.data.room),p=room?.players.find(x=>x.id===socket.id);bet=Math.max(100,Math.min(+bet||100,5000,p?.chips||0));if(!p)return cb({ok:false});p.chips-=bet;room.roulette.bets.push({id:p.id,name:p.name,bet,choice});cb({ok:true});emitRoom(room.code)});socket.on('rouletteSpin',()=>{const room=rooms.get(socket.data.room);if(!room)return;const n=Math.floor(Math.random()*37);const red=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36].includes(n);const color=n===0?'green':red?'red':'black';room.roulette.last={n,color};for(const b of room.roulette.bets){const p=room.players.find(x=>x.id===b.id);if(!p)continue;let win=0;if(String(b.choice)===String(n))win=b.bet*36;else if(b.choice===color)win=b.bet*2;p.chips+=win}room.roulette.bets=[];emitRoom(room.code)});
socket.on('disconnect',()=>{const r=socket.data.room,room=rooms.get(r);if(!room)return;const p=room.players.find(x=>x.id===socket.id);if(p){p.id=null;p.status='Disconnected'}emitRoom(r)})});
server.listen(process.env.PORT||3000,()=>console.log('Goonateer Casino running on http://localhost:3000'));
