const express=require('express');const http=require('http');const {Server}=require('socket.io');
const app=express();const server=http.createServer(app);const io=new Server(server);app.use(express.static('public'));
const rooms={};
const suits=['♠','♥','♦','♣'];const ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
function code(){let s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',c='';for(let i=0;i<6;i++)c+=s[Math.floor(Math.random()*s.length)];return c}
function deck(){let d=[];for(const s of suits)for(const r of ranks)d.push({r,s});return d.sort(()=>Math.random()-.5)}
function val(cards){let total=0,aces=0;for(const c of cards){if(c.r==='A'){aces++;total+=11}else if(['K','Q','J'].includes(c.r))total+=10;else total+=+c.r}while(total>21&&aces){total-=10;aces--}return total}
function sanitize(room){return {code:room.code,game:room.game,players:room.players.map((p,i)=>({...p,index:i,cards:p.cards||[],handValue:val(p.cards||[])})),blackjack: room.blackjack?{dealerUp:room.blackjack.dealerRevealed?room.blackjack.dealerCards:room.blackjack.dealerCards.map((c,i)=>i===0?{hidden:true}:c),dealerValue:room.blackjack.dealerRevealed?val(room.blackjack.dealerCards):val(room.blackjack.dealerCards.slice(1)),phase:room.blackjack.phase,currentTurn:room.blackjack.currentTurn,message:room.blackjack.message}:null}}
function emit(room){io.to(room.code).emit('state',sanitize(room))}
function makeRoom(){let c;do c=code();while(rooms[c]);rooms[c]={code:c,game:null,players:[],blackjack:null};return rooms[c]}
function ensureBJ(room){room.game='blackjack';room.blackjack={deck:deck(),dealerCards:[],phase:'betting',currentTurn:0,dealerRevealed:false,message:'Place your bets'};room.players.forEach(p=>{p.bet=500;p.cards=[];p.status='betting';});}
function startBJ(room){const bj=room.blackjack;bj.deck=deck();bj.dealerCards=[bj.deck.pop(),bj.deck.pop()];bj.phase='playing';bj.dealerRevealed=false;bj.currentTurn=0;room.players.forEach(p=>{p.cards=[bj.deck.pop(),bj.deck.pop()];p.status='playing';p.bet=p.bet||500});bj.message=`${room.players[0]?.name||'Player 1'}'s turn`;skipDone(room)}
function skipDone(room){const bj=room.blackjack;while(bj.currentTurn<room.players.length&&(room.players[bj.currentTurn].status==='stand'||room.players[bj.currentTurn].status==='bust')) bj.currentTurn++;if(bj.currentTurn>=room.players.length) dealerPlay(room); else bj.message=`${room.players[bj.currentTurn].name}'s turn`;}
function dealerPlay(room){const bj=room.blackjack;bj.phase='dealer';bj.dealerRevealed=true;while(val(bj.dealerCards)<17)bj.dealerCards.push(bj.deck.pop());const dv=val(bj.dealerCards);room.players.forEach(p=>{const pv=val(p.cards); if(p.status==='bust'){p.result='Bust';p.chips-=p.bet}else if(dv>21||pv>dv){p.result='Win';p.chips+=p.bet}else if(pv===dv){p.result='Push'}else{p.result='Lose';p.chips-=p.bet}p.status='done'});bj.phase='roundover';bj.message=dv>21?'Dealer busts!':'Round complete';}
io.on('connection',socket=>{
 socket.on('createRoom',({name},cb)=>{const room=makeRoom();const p={id:socket.id,name:name||'Player',chips:100000,cards:[],bet:500,status:'lobby'};room.players.push(p);socket.join(room.code);cb&&cb({ok:true,code:room.code});emit(room)});
 socket.on('joinRoom',({code,name},cb)=>{const room=rooms[(code||'').toUpperCase()];if(!room)return cb&&cb({ok:false,error:'Room not found'});if(room.players.length>=10)return cb&&cb({ok:false,error:'Room full'});room.players.push({id:socket.id,name:name||'Player',chips:100000,cards:[],bet:500,status:'lobby'});socket.join(room.code);cb&&cb({ok:true,code:room.code});emit(room)});
 socket.on('chooseGame',({code,game})=>{const room=rooms[code];if(!room)return;room.game=game;if(game==='blackjack')ensureBJ(room);emit(room)});
 socket.on('bjStart',({code})=>{const room=rooms[code];if(!room||room.game!=='blackjack')return;startBJ(room);emit(room)});
 socket.on('bjBet',({code,amount})=>{const room=rooms[code];if(!room||!room.blackjack)return;const p=room.players.find(x=>x.id===socket.id);if(p&&room.blackjack.phase==='betting')p.bet=Math.max(100,Math.min(p.chips,amount||500));emit(room)});
 socket.on('bjHit',({code})=>{const room=rooms[code];if(!room||!room.blackjack)return;const bj=room.blackjack;const p=room.players[bj.currentTurn];if(!p||p.id!==socket.id||bj.phase!=='playing')return;p.cards.push(bj.deck.pop());if(val(p.cards)>21)p.status='bust';skipDone(room);emit(room)});
 socket.on('bjStand',({code})=>{const room=rooms[code];if(!room||!room.blackjack)return;const bj=room.blackjack;const p=room.players[bj.currentTurn];if(!p||p.id!==socket.id||bj.phase!=='playing')return;p.status='stand';bj.currentTurn++;skipDone(room);emit(room)});
 socket.on('bjDouble',({code})=>{const room=rooms[code];if(!room||!room.blackjack)return;const bj=room.blackjack;const p=room.players[bj.currentTurn];if(!p||p.id!==socket.id||bj.phase!=='playing'||p.cards.length!==2)return;p.bet=Math.min(p.chips,p.bet*2);p.cards.push(bj.deck.pop());p.status=val(p.cards)>21?'bust':'stand';bj.currentTurn++;skipDone(room);emit(room)});
 socket.on('bjNewRound',({code})=>{const room=rooms[code];if(!room)return;ensureBJ(room);emit(room)});
 socket.on('disconnect',()=>{for(const c in rooms){const r=rooms[c];const before=r.players.length;r.players=r.players.filter(p=>p.id!==socket.id);if(before!==r.players.length)emit(r);if(r.players.length===0)delete rooms[c];}})
});
server.listen(process.env.PORT||3000,()=>console.log('Goonateer Casino running'));
